export const OFFER_REGISTER_REQUEST = 'OFFER_REGISTER_REQUEST';
export const OFFER_REGISTER_SUCCESS = 'OFFER_REGISTER_SUCCESS';
export const OFFER_REGISTER_FAILED = 'OFFER_REGISTER_FAILED';

export const OFFER_RECEIVED_REQUEST = 'OFFER_RECEIVED_REQUEST';
export const OFFER_RECEIVED_SUCCESS = 'OFFER_RECEIVED_SUCCESS';
export const OFFER_RECEIVED_FAILED = 'OFFER_RECEIVED_FAILED';

export const OFFER_SENT_REQUEST = 'OFFER_SENT_REQUEST';
export const OFFER_SENT_SUCCESS = 'OFFER_SENT_SUCCESS';
export const OFFER_SENT_FAILED = 'OFFER_SENT_FAILED';

export const OFFER_ANSWER_REQUEST = 'OFFER_ANSWER_REQUEST';
export const OFFER_ANSWER_SUCCESS = 'OFFER_ANSWER_SUCCESS';
export const OFFER_ANSWER_FAILED = 'OFFER_ANSWER_FAILED';