export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED';

export const PRODUCT_REGISTER_REQUEST = 'PRODUCT_REGISTER_REQUEST';
export const PRODUCT_REGISTER_SUCCESS = 'PRODUCT_REGISTER_SUCCESS';
export const PRODUCT_REGISTER_FAILED = 'PRODUCT_REGISTER_FAILED';